---

- name: Create sudoers.d file
  template:
    src: mariadb.sudoers
    dest: /etc/sudoers.d/mariadb.sudoers
    owner: root
    group: root
    mode: "0440"
  tags:
    - sudo
    - secure
    - configure

- name: Create mariadb-server.cnf template
  template:
    src: mariadb-server.cnf
    dest: "{{ mariadb_conf_dir}}/mariadb-server.cnf"
    owner: root
    group: root
    mode: "0644"
  notify: restart mariadb
  tags:
    - configure

- name: Create configuration files
  template:
    src: "{{ item }}"
    dest: "{{ mariadb_conf_dir }}/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - mysql-clients.cnf
  notify: restart mariadb
  tags:
    - configure

- name: Create systemd overrides directory
  when: ansible_distribution_major_version is version('6', '>')
  file:
    path: "{{ mariadb_overrides_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configure

- name: Manage systemd limits
  when: ansible_distribution_major_version is version('6', '>')
  template:
    src: limits.conf
    dest: "{{ mariadb_overrides_dir }}"
    owner: root
    group: root
    mode: 0644
  notify: reload deamon
  tags:
    - configure

- name: Flush handlers
  meta: flush_handlers
  tags:
    - configure

- name: Ensure mariadb is running
  service:
    name: "{{ mariadb_service }}"
    enabled: true
    state: started

...
