---

- name: Create databases
  mysql_db:
    name: "{{ item.name }}"
    state: present
  loop: "{{ mariadb_databases }}"
  when: not item.delete|default(False)
  tags:
    - resources

- name: Grant local users to the databases
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.pass }}"
    priv: "{{ item.name }}.*:ALL"
    append_privs: true
    state: present
  loop: "{{ mariadb_databases }}"
  when: item.ip is not defined and not item.delete|default(False)
  tags:
    - resources

- name: Grant remote users to the databases
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.pass }}"
    host: "%"
    priv: "{{ item.name }}.*:ALL"
    state: present
    append_privs: false
  loop: "{{ mariadb_databases }}"
  when: item.ip is defined and not item.delete|default(False)
  tags:
    - resources
