---

- name: Install Centos software collections
  package:
    name: centos-release-scl-rh
    state: present
  register: network_access
  until: network_access is success
  retries: 3
  delay: 4
  when: collections_enabled|bool and ansible_distribution == 'CentOS'
  tags:
    - mariadb

- name: Enable RHEL software collections
  # yamllint disable-line rule:line-length
  command: "yum-config-manager --enable rhel-server-rhscl-{{ ansible_distribution_major_version }}-rpms"
  when: collections_enabled|bool and ansible_distribution == 'RedHat'
  tags:
    - mariadb

- name: Install MariaDB from Software Collections
  when: collections_enabled|bool and ansible_os_family == 'RedHat'
  yum:
    name: "{{ mariadb_packages }}"
    state: present
    update_cache: true
  register: installed
  until: installed is success
  retries: 5
  delay: 5
  tags:
    - mariadb

- name: Install packages with Python libraries
  when: ansible_distribution_major_version is version('8', '<')
  yum:
    name:
      - MySQL-python
      - policycoreutils-python
      - libsemanage-python
    state: present
  register: installed
  until: installed is success
  retries: 1
  delay: 3

- name: Install mysqltuner from EPEL
  when: ansible_os_family == 'RedHat'
  yum:
    name: mysqltuner
    state: present
  register: downloaded
  until: downloaded is success
  retries: 3
  delay: 3
  ignore_errors: true
  tags:
    - mariadb

...
