---

- name: Install packages
  include_tasks: install.yml

- name: Install tmpfs
  include_tasks: tmpfs.yml

- name: Configure mariadb
  include_tasks: configure.yml

- name: Test for .my.cnf
  stat:
    path: /root/.my.cnf
  register: my_cnf

- name: Create users
  include_tasks: users.yml
  when: not my_cnf.stat.exists

- name: Create databases
  include_tasks: databases.yml
