---

- name: reload deamon
  systemd:
    name: "{{ mariadb_service }}"
    daemon_reload: true

- name: restart mariadb
  service:
    name: "{{ mariadb_service }}"
    state: restarted


- name: start mariadb
  service:
    name: "{{ mariadb_service }}"
    state: started
