---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: base-mariadb-centos7
    image: milcom/centos7-systemd
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
